### ISSUE TITLE
Release in IntelliJ marketplace?

### ISSUE THREAD

**Issue by prydonius** [nerro/intellij-codeowners-plugin#1]
I'm trying to get the functionality of this VS Code plugin in IntelliJ: https://marketplace.visualstudio.com/items?itemName=jasonnutter.vscode-codeowners. Does this plugin do this? How can I install it? Would it be possible to publish it to the IntelliJ marketplace?

**Comment by fan-tom** [comment]
Hi @prydonius, there is no functionality in this plugin yet, it is just blank project. I develop my own version of that plugin and will publish it to Intellij marketplace soon

**Comment by prydonius** [comment]
@fan-tom sounds great, please let us know when you've published it

**Comment by nerro** [comment]
:) I'm glad you can use my project skeleton for creating a plugin with this functionality. Because of work I'll pretty busy until the end of summer.

Feel free to improve/work on the work. I'm going to close the issue.
